-- Fix admin user password hash
UPDATE users SET password_hash = '$2a$12$MT5v0PEpEoWFlbGXL4ASJObt88XsQS3iowfCU3qca5x0fkGfAEKvC' WHERE id = 1 AND username = 'admin';

-- Seed default dispatch codes
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-1', 'Signal Weak / Poor Reception', 'Signal', 'P3');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-2', 'Signal Good', 'Signal', 'P3');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-3', 'Stop Transmitting', 'Signal', 'P3');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-4', 'Affirmative / OK', 'Status', 'P3');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-5', 'Relay', 'Action', 'P3');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-6', 'Busy', 'Status', 'P3');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-7', 'Out of Service', 'Status', 'P3');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-8', 'In Service / Available', 'Status', 'P3');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-9', 'Repeat', 'Action', 'P3');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-10', 'Fight In Progress', 'Priority', 'P1');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-11', 'Traffic Stop', 'Traffic', 'P2');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-12', 'Stand By', 'Status', 'P3');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-13', 'Weather / Road Conditions', 'Info', 'P3');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-14', 'Suspicious Person', 'Priority', 'P2');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-15', 'Suspicious Vehicle', 'Priority', 'P2');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-16', 'Domestic Disturbance', 'Priority', 'P1');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-17', 'Burglary', 'Priority', 'P1');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-18', 'Robbery', 'Priority', 'P1');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-19', 'Shots Fired', 'Priority', 'P1');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-20', 'Location', 'Info', 'P3');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-21', 'Phone Call', 'Action', 'P3');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-22', 'Disregard', 'Action', 'P3');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-23', 'Arrived at Scene', 'Status', 'P2');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-24', 'Assignment Complete', 'Status', 'P2');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-25', 'Report In Person', 'Action', 'P3');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-26', 'Detaining Subject', 'Action', 'P2');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-27', 'Drivers License Check', 'Traffic', 'P2');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-28', 'Vehicle Registration Check', 'Traffic', 'P2');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-29', 'Warrant Check', 'Traffic', 'P2');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-30', 'Officer Needs Help (Emergency)', 'Emergency', 'P1');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-31', 'Pursuit', 'Emergency', 'P1');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-32', 'Request Backup', 'Action', 'P1');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-33', 'Emergency Traffic', 'Emergency', 'P1');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-34', 'Clear for Next Assignment', 'Action', 'P3');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-35', 'Request Mobile Command', 'Action', 'P2');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-50', 'Accident (Property Damage)', 'Traffic', 'P2');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-51', 'Accident (Injury)', 'Traffic', 'P1');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-52', 'Accident (Fatality)', 'Traffic', 'P1');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-53', 'Road Blocked', 'Traffic', 'P2');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-54', 'DUI / Intoxicated Driver', 'Traffic', 'P1');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-55', 'Reckless Driver', 'Traffic', 'P2');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-60', 'Subject Armed', 'Priority', 'P1');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-61', 'Subject Wanted', 'Priority', 'P1');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-62', 'Subject Mentally Ill', 'Priority', 'P2');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-63', 'Subject Intoxicated', 'Priority', 'P3');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-64', 'Subject on Drugs', 'Priority', 'P2');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-65', 'K9 Response Needed', 'Action', 'P2');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-66', 'Hostage Situation', 'Emergency', 'P1');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-70', 'Fire', 'Priority', 'P1');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-71', 'Alarm', 'Priority', 'P2');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-72', 'Medical Emergency', 'Priority', 'P1');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-80', 'SWAT / Tactical', 'Emergency', 'P1');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-90', 'Narcotics Activity', 'Priority', 'P2');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-91', 'Trespassing', 'Priority', 'P3');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-92', 'Welfare Check', 'Priority', 'P2');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-93', 'Check Security', 'Action', 'P3');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-94', 'Abandoned Vehicle', 'Traffic', 'P3');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-95', 'Noise Complaint', 'Priority', 'P3');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-96', 'Civil Matter', 'Priority', 'P3');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-97', 'Animal Complaint', 'Priority', 'P3');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-98', 'Fireworks Complaint', 'Priority', 'P3');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('10-99', 'Warrant Service', 'Action', 'P2');

-- Seed default incident types
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('911', '911 Hangup / Open Line', 'Priority', 'P1');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('ABAN', 'Abandoned Property', 'Priority', 'P3');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('ABDU', 'Abduction / Kidnapping', 'Emergency', 'P1');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('ABUSE', 'Child / Elder Abuse', 'Priority', 'P1');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('ALARM', 'Alarm Activation', 'Priority', 'P2');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('ASSAULT', 'Assault', 'Priority', 'P1');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('BURG', 'Burglary', 'Priority', 'P1');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('CIVIL', 'Civil Matter', 'Priority', 'P3');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('DOM', 'Domestic Disturbance', 'Priority', 'P1');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('DUI', 'DUI / Impaired Driving', 'Traffic', 'P1');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('FIRE', 'Fire', 'Emergency', 'P1');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('FRAUD', 'Fraud / Forgery', 'Priority', 'P2');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('HARAS', 'Harassment', 'Priority', 'P2');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('HOMI', 'Homicide', 'Emergency', 'P1');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('INTOX', 'Intoxicated Person', 'Priority', 'P3');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('JUV', 'Juvenile Matter', 'Priority', 'P2');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('LARC', 'Larceny / Theft', 'Priority', 'P2');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('MISC', 'Miscellaneous', 'Priority', 'P3');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('MISS', 'Missing Person', 'Priority', 'P1');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('NARC', 'Narcotics Violation', 'Priority', 'P2');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('NOISE', 'Noise Complaint', 'Priority', 'P3');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('ORDER', 'Protection / Restraining Order', 'Priority', 'P2');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('PROWL', 'Prowler / Suspicious', 'Priority', 'P2');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('ROBB', 'Robbery', 'Emergency', 'P1');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('SEX', 'Sex Offense', 'Emergency', 'P1');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('SHOTS', 'Shots Fired', 'Emergency', 'P1');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('SUIC', 'Suicide Threat / Attempt', 'Emergency', 'P1');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('TRAF', 'Traffic Accident', 'Traffic', 'P2');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('TRESP', 'Trespassing', 'Priority', 'P3');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('VAND', 'Vandalism', 'Priority', 'P3');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('VEH', 'Abandoned / Stolen Vehicle', 'Traffic', 'P2');
INSERT OR IGNORE INTO dispatch_codes (code, description, category, priority) VALUES ('WELF', 'Welfare Check', 'Priority', 'P2');

-- Seed default geography
INSERT OR IGNORE INTO dispatch_areas (id, code, name, color, sort_order) VALUES (1, 'N', 'North Area', '#E53935', 1);
INSERT OR IGNORE INTO dispatch_areas (id, code, name, color, sort_order) VALUES (2, 'S', 'South Area', '#1E88E5', 2);
INSERT OR IGNORE INTO dispatch_areas (id, code, name, color, sort_order) VALUES (3, 'E', 'East Area', '#43A047', 3);
INSERT OR IGNORE INTO dispatch_areas (id, code, name, color, sort_order) VALUES (4, 'W', 'West Area', '#FB8C00', 4);

INSERT OR IGNORE INTO dispatch_sectors (id, area_id, code, name, sort_order) VALUES (1, 1, 'N1', 'North Sector 1', 1);
INSERT OR IGNORE INTO dispatch_sectors (id, area_id, code, name, sort_order) VALUES (2, 1, 'N2', 'North Sector 2', 2);
INSERT OR IGNORE INTO dispatch_sectors (id, area_id, code, name, sort_order) VALUES (3, 2, 'S1', 'South Sector 1', 1);
INSERT OR IGNORE INTO dispatch_sectors (id, area_id, code, name, sort_order) VALUES (4, 2, 'S2', 'South Sector 2', 2);
INSERT OR IGNORE INTO dispatch_sectors (id, area_id, code, name, sort_order) VALUES (5, 3, 'E1', 'East Sector 1', 1);
INSERT OR IGNORE INTO dispatch_sectors (id, area_id, code, name, sort_order) VALUES (6, 3, 'E2', 'East Sector 2', 2);
INSERT OR IGNORE INTO dispatch_sectors (id, area_id, code, name, sort_order) VALUES (7, 4, 'W1', 'West Sector 1', 1);
INSERT OR IGNORE INTO dispatch_sectors (id, area_id, code, name, sort_order) VALUES (8, 4, 'W2', 'West Sector 2', 2);

UPDATE system_config SET value = '1.0.1' WHERE key = 'db_version';
